# Generated by Django 3.2.5 on 2021-08-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=8)),
                ('last_name', models.CharField(max_length=8)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=13)),
                ('nationality', models.CharField(choices=[('Kenya', 'Kenya'), ('Uganda', 'Uganda'), ('Sudan', 'Sudan')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=13)),
                ('bank_account', models.IntegerField()),
                ('profession', models.CharField(max_length=30)),
                ('salary', models.PositiveBigIntegerField()),
                ('trainer_contract', models.FileField(upload_to='')),
                ('id_number', models.IntegerField()),
                ('course', models.CharField(max_length=12)),
                ('cv', models.FileField(upload_to='documents/')),
                ('contract', models.FileField(upload_to='documents/')),
                ('profile_picture', models.ImageField(upload_to='pictures/')),
            ],
        ),
    ]
