# Generated by Django 3.2.5 on 2021-07-31 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_alter_trainer_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='experience',
        ),
    ]
