# Generated by Django 3.2.5 on 2021-09-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_merge_20210902_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
