# Generated by Django 3.2.5 on 2021-09-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_auto_20210903_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
