# Generated by Django 3.2.5 on 2021-09-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_alter_trainer_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='contract/'),
        ),
    ]
