# Generated by Django 3.2.5 on 2021-08-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=10)),
                ('event_month', models.CharField(max_length=10)),
                ('event_date', models.DateTimeField()),
                ('event_organizer', models.CharField(max_length=10)),
                ('event_duration', models.TimeField()),
                ('event_golds', models.CharField(max_length=14)),
                ('event_appoved', models.CharField(max_length=12)),
                ('event_attented_by', models.CharField(max_length=3)),
            ],
        ),
    ]
