# Generated by Django 3.2.5 on 2021-08-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='event_date',
            field=models.DateTimeField(blank=2, null=True),
        ),
    ]
