# Generated by Django 3.2.5 on 2021-09-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_alter_calendar_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='event_appoved',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='event_attented_by',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='event_duration',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='event_goals',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='event_month',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='event_organizer',
        ),
        migrations.AddField(
            model_name='calendar',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendar',
            name='end_time',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendar',
            name='start_time',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendar',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
