# Generated by Django 3.2.5 on 2021-09-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0004_auto_20210907_1241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
