# Generated by Django 3.2.5 on 2021-07-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=8)),
                ('last_name', models.CharField(max_length=8)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('nationality', models.CharField(choices=[('K', 'Kenya'), ('U', 'Uganda'), ('S', 'Sudan')], max_length=1)),
                ('profile_picture', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('bank_account', models.IntegerField()),
                ('trainer_contract', models.FileField(upload_to='')),
                ('profession', models.CharField(max_length=30)),
                ('salary', models.PositiveBigIntegerField()),
                ('trainer_CV', models.FileField(upload_to='')),
                ('id_number', models.IntegerField()),
                ('experience', models.PositiveSmallIntegerField(max_length=5)),
                ('contract', models.FileField(upload_to='')),
            ],
        ),
    ]
