# Generated by Django 3.2.5 on 2021-09-02 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_auto_20210826_1256'),
        ('trainer', '0003_remove_trainer_experience'),
    ]

    operations = [
    ]
