# Generated by Django 3.2.5 on 2021-08-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='e.g Aisha', max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('age', models.PositiveSmallIntegerField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('nationality', models.CharField(choices=[('Kenya', 'Kenya'), ('Sudan', 'Sudan'), ('Uganda', 'Uganda'), ('Rwanda', 'Rwanda')], max_length=10)),
                ('county', models.CharField(default='Valid', max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('id_passport', models.CharField(max_length=12)),
                ('parent_name', models.CharField(max_length=12)),
                ('parent_contact', models.CharField(max_length=13)),
                ('medical_report', models.FileField(upload_to='')),
                ('registration_number', models.PositiveSmallIntegerField()),
                ('room_number', models.CharField(max_length=8)),
                ('big_sister', models.CharField(default='Valid', max_length=10)),
                ('class_name', models.CharField(max_length=10)),
                ('mentor_name', models.CharField(max_length=10)),
                ('passport_photo', models.ImageField(blank=True, default='demo-artist.jpg', null=True, upload_to='artists/%Y/%m/%d/')),
                ('language', models.CharField(choices=[('English', 'English'), ('Kiswahili', 'Kiswahili'), ('Arabic', 'Arabic'), ('Others', 'Others')], max_length=10)),
                ('laptop_number', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
    ]
