# Generated by Django 3.2.5 on 2021-07-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='County',
            field=models.CharField(default='Valid', max_length=12),
        ),
        migrations.AddField(
            model_name='student',
            name='big_sister',
            field=models.CharField(default='Valid', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='id_passport',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='language',
            field=models.CharField(choices=[('E', 'English'), ('K', 'Kiswahili'), ('A', 'Arabic'), ('L', 'Local')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='medical_report',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mentor_name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('K', 'Kenya'), ('S', 'Sudan'), ('U', 'Uganda'), ('R', 'Rwanda')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='parent_contact',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='parent_name',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='passport_photo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.PositiveIntegerField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='registration_number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='room_number',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
