# Generated by Django 3.2.5 on 2021-07-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210730_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passport_photo',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.PositiveIntegerField(),
        ),
    ]
