# Generated by Django 3.2.5 on 2021-08-17 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210813_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='medical_report',
        ),
        migrations.RemoveField(
            model_name='student',
            name='passport_photo',
        ),
    ]
