# Generated by Django 3.2.5 on 2021-09-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210817_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='medical_report',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='passport_photo',
            field=models.ImageField(blank=True, default='demo-artist.jpg', null=True, upload_to='artists/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Kiswahili', 'Kiswahili'), ('Arabic', 'Arabic'), ('Others', 'Others')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('Kenya', 'Kenya'), ('Sudan', 'Sudan'), ('Uganda', 'Uganda'), ('Rwanda', 'Rwanda')], max_length=10),
        ),
    ]
