# Generated by Django 3.2.5 on 2021-08-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_student_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='County',
            new_name='county',
        ),
        migrations.AddField(
            model_name='student',
            name='laptop_number',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(help_text='e.g Aisha', max_length=10),
        ),
    ]
