# Generated by Django 3.2.5 on 2021-09-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20210903_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
